### PR TITLE
private funcs

### PR DESCRIPTION
**Pull request by evilbat831**

### CODE REVIEW

**Comment by evilbat831** [comment]
hi sir i have added some private funcs pls check it out

**Comment by krishpranav** [comment]
hi @evilbat831 i will check it

**Comment by evilbat831** [comment]
ok sir

**Comment by krishpranav** [comment]
so i have checked the private funcs for Func.h. Thanks for adding this stuff

**Comment by evilbat831** [comment]
your always welcome sir

**Pull request merged**
