### PR TITLE
Kernel: keyboard support

### PR DESCRIPTION
**Pull request by biggboy021**
hey @krishpranav i have added keyboard support for pranaOS kernel[supports ps2 + usb keyboard]
hope you like it and this is just a header file i didnt add the main func

### CODE REVIEW

**Review by krishpranav — COMMENTED** [review]
hey @biggboy021 the keyboard header one's is great i you need to change one thing

- keyboardmanager.h:
```c++
             void handleKeyChange(Keyboard* src, uint32_t key, int pressed); ->              void handleKeyChange(Keyboard* src, uint32_t key, bool pressed);
```

- change the int pressed -> bool pressed cause we want to print it in the log if it is int it will return the status code

**Review by krishpranav — COMMENTED** [review]
change the review

**Comment by biggboy021** [comment]
sure i will change your changes

**Comment by biggboy021** [comment]
hey i have updated

**Comment by krishpranav** [comment]
thanks for adding the stuff this is a great one!

**Pull request merged**
