### PR TITLE
tags header

### PR DESCRIPTION
**Pull request by samvirg-git**
hi @krishpranav check the thing I just added some auto constexpr for enum values
first pull request of me @samvirg-git 
authors: @krishpranav, @samvirg-git

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @samvirg-git great let me check the things you've added!!

**Comment by samvirg-git** [comment]
hi @krishpranav hope you like the thing that I added I just added the constexpr auto values for the enum values I've added that willl be useful for other header files your going to create all around pranaOS! :)

**Comment by krishpranav** [comment]
> hi @krishpranav hope you like the thing that I added I just added the constexpr auto values for the enum values I've added that willl be useful for other header files your going to create all around pranaOS! :)

that's great @samvirg-git

**Comment by krishpranav** [comment]
__MERGED__

**Comment by samvirg-git** [comment]
thanks my first pr I am so happy!! :)

**Comment by krishpranav** [comment]
;)

**Comment by krishpranav** [comment]
pr's are always welcome ;)

**Comment by samvirg-git** [comment]
thanks!!

**Pull request merged**
