### PR TITLE
fixed: #ifndef -> #pragma once 

### PR DESCRIPTION
**Pull request by ASPECThalalexmine**
hello sir I just saw the issue:
[issue 99](https://github.com/pranaOS/pranaOS/issues/99)

I have just changed from #ifndef -> #pragma once in some sys files under libc 

I hope you like the work that I have made :) 

Regards,
@ASPECThalalexmine

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @ASPECThalalexmine it is a great thing you have added I think so this is your first pr ;)

**Comment by krishpranav** [comment]
there is no checks on your work cause all good ;)

**Comment by krishpranav** [comment]
__MERGED__

**Comment by ASPECThalalexmine** [comment]
thank you sir

**Comment by ASPECThalalexmine** [comment]
> MERGED

ohh my god thanks!!! 👍

**Pull request merged**
