### PR TITLE
handle client functions

### PR DESCRIPTION
**Pull request by nuke123-sudo**

### CODE REVIEW

**Comment by nuke123-sudo** [comment]
hi @krishpranav I have added some handles functions

**Comment by nuke123-sudo** [comment]
check it out.

**Comment by Andrew-stew** [comment]
hi @nuke123-sudo I have seen your work in pranaOS awesome man!!

**Comment by nuke123-sudo** [comment]
thanks @Andrew-stew

**Comment by Andrew-stew** [comment]
how are you doing these things??

**Comment by nuke123-sudo** [comment]
I am in c++ field for some years

**Comment by nuke123-sudo** [comment]
so I have a couple of experience in these type of project

**Comment by Andrew-stew** [comment]
ok cool 👍

**Comment by krishpranav** [comment]
hi @nuke123-sudo I will see the code and tell you.

**Comment by nuke123-sudo** [comment]
ok sure @krishpranav 👍

**Comment by krishpranav** [comment]
awesome work 👍🏻 👍🏻

**Comment by nuke123-sudo** [comment]
thanks

**Pull request merged**
