### PR TITLE
changes: fix #ifndef -> #pragma once

### PR DESCRIPTION
**Pull request by OliviaCE**
changes: fix #ifndef -> #pragma once
author: @krishpranav
co-author: @OliviaCE 

hey @krishpranav I have changed from #ifndef -> #pragma once in most of the files I hope you like it :)

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @OliviaCE it is a great thing appreciate it let me check out these things and tell you can I __MERGE__ it or not

**Comment by OliviaCE** [comment]
> hey @OliviaCE it is a great thing appreciate it let me check out these things and tell you can I **MERGE** it or not

yea sure

**Comment by krishpranav** [comment]
great thing waiting for checks to pass

**Comment by OliviaCE** [comment]
ok 👍

**Comment by krishpranav** [comment]
__MERGED__

**Comment by OliviaCE** [comment]
;)

**Pull request merged**
