### PR TITLE
SB16

### PR DESCRIPTION
**Pull request by AakeshDarsh**
Things Added:
SB16 speakers connecting & making it as output

### CODE REVIEW

**Comment by AakeshDarsh** [comment]
hi @krishpranav I've added some sb16 speaker functions

**Comment by AakeshDarsh** [comment]
need to develop it

**Comment by krishpranav** [comment]
ok that's a great thing @AakeshDarsh

**Comment by krishpranav** [comment]
I will develop it but the thing you've added is fabulous

**Comment by AakeshDarsh** [comment]
thank you @krishpranav

**Comment by krishpranav** [comment]
__MERGED__

**Pull request merged**
