### PR TITLE
fuzz values

### PR DESCRIPTION
**Pull request by nuke123-sudo**
hi @krishpranav I have added:
Fuzzing functions for
BmpLoader
CyrillicDecoder
DeflateCompression
DeflateDecompression
ELF
FlacLoader
GIFLoder

### CODE REVIEW

**Comment by krishpranav** [comment]
hi @nuke123-sudo I will review It

**Comment by krishpranav** [comment]
great work the libraries you have mentioned will be added soon

**Comment by nuke123-sudo** [comment]
ok great

**Comment by krishpranav** [comment]
great work __MERGED__

**Comment by nuke123-sudo** [comment]
👍

**Pull request merged**
