### PR TITLE
lexicalpath functions

### PR DESCRIPTION
**Pull request by Alex5xt**

### CODE REVIEW

**Comment by Alex5xt** [comment]
hi @krishpranav i have added lexicalpath functions check it out!

**Comment by krishpranav** [comment]
hi @Alex5xt i will check the code and tell you

**Comment by Alex5xt** [comment]
ok sure take your own time

**Comment by krishpranav** [comment]
great work need to develop more i will do those stuffs

**Comment by Alex5xt** [comment]
thank you

**Pull request merged**
