### PR TITLE
ownptr public functions

### PR DESCRIPTION
**Pull request by Alex5xt**

### CODE REVIEW

**Comment by Alex5xt** [comment]
hi @krishpranav i have added ownptr headers pls check it out

**Comment by krishpranav** [comment]
hi @Alex5xt so i will check it

**Comment by Alex5xt** [comment]
ok sir

**Comment by krishpranav** [comment]
you have defined some operators good.

**Comment by krishpranav** [comment]
need to develop more but thanks for adding this stuff.

**Comment by Alex5xt** [comment]
ok sir

**Comment by krishpranav** [comment]
merged!

**Pull request merged**
