### PR TITLE
partitions functions

### PR DESCRIPTION
**Pull request by evilbat831**

### CODE REVIEW

**Comment by evilbat831** [comment]
hi @krishpranav I have added partition functions.
_check it out_

**Comment by krishpranav** [comment]
ok I will check it and tell you.

**Comment by evilbat831** [comment]
ok 👍

**Comment by krishpranav** [comment]
great work 👍🏻

**Comment by krishpranav** [comment]
merged

**Comment by evilbat831** [comment]
thanks

**Pull request merged**
