### PR TITLE
Kernel: core gdtentry header

### PR DESCRIPTION
**Pull request by biggboy021**
hey @krishpranav i have added gdt common entry header 

to know what is gdt check out here a nice example from osdev: https://forum.osdev.org/viewtopic.php?f=1&t=11752

author: @biggboy021

### CODE REVIEW

**Review by krishpranav — CHANGES_REQUESTED** [review]
can you change the static class name
```c++
SetDescriptor -> setDescriptor
GetDescriptor getDescriptor
```

it would be great if you change this two things :)

**Comment by biggboy021** [comment]
yea sure @krishpranav

**Comment by biggboy021** [comment]
hey can you check those now?

**Comment by krishpranav** [comment]
yep sure

**Review by krishpranav — COMMENTED** [review]
fabulous⭐

**Comment by krishpranav** [comment]
__MERGED__

**Pull request merged**
