### PR TITLE
cpu id headers

### PR DESCRIPTION
**Pull request by Andrew-stew**
hi sir i have fixed some issues in the code please review it

### CODE REVIEW

**Comment by krishpranav** [comment]
hi @michaelsmith213 so i will review it

**Comment by Andrew-stew** [comment]
ok sir

**Comment by krishpranav** [comment]
you have added union packed right?

**Comment by Andrew-stew** [comment]
yes sir

**Comment by krishpranav** [comment]
ok great work man!

**Comment by Andrew-stew** [comment]
thanks sir

**Comment by krishpranav** [comment]
merged!.

**Pull request merged**
