### PR TITLE
MemoryDevice

### PR DESCRIPTION
**Pull request by AakeshDarsh**
Things I've added:
MemoryDevice.cpp
MemoryDevice.h

Features I've Added:
- MemoryDevice.cpp
```sh
Phyiscal Memory Mapping Function
did seek
```

### CODE REVIEW

**Comment by AakeshDarsh** [comment]
added some memory device headers & functions

**Comment by krishpranav** [comment]
hi @AakeshDarsh I will review it and tell you

**Comment by AakeshDarsh** [comment]
ok sure!

**Comment by krishpranav** [comment]
great work @AakeshDarsh

**Comment by AakeshDarsh** [comment]
thanks! @krishpranav first time contributing to a open source project

**Comment by krishpranav** [comment]
great!!!

**Comment by AakeshDarsh** [comment]
I have 1 year of c++ experience so only I contributed to you

**Comment by krishpranav** [comment]
ok great

**Comment by krishpranav** [comment]
you interested in joining pranaOS?

**Comment by AakeshDarsh** [comment]
yea sure I am too interested

**Comment by krishpranav** [comment]
I saw you code so I am directly inviting you to pranaOS

**Comment by AakeshDarsh** [comment]
ok @krishpranav

**Comment by krishpranav** [comment]
join our discord server:
https://discord.gg/XmpBTmy9Bz

**Comment by krishpranav** [comment]
check your email and join discord server

**Comment by AakeshDarsh** [comment]
ok sir

**Comment by krishpranav** [comment]
__MERGED__

**Pull request merged**
