### PR TITLE
cpu: poweroff, reboot, tss

### PR DESCRIPTION
**Pull request by biggboy021**
hi @krishpranav i have added poweroff, reboot, tssentry headers hope it would be helpfull while working on the main 

tss: TaskStateSegment

### CODE REVIEW

**Comment by krishpranav** [comment]
hey Chester this are great work let me review them

**Review by krishpranav — CHANGES_REQUESTED** [review]
reboot and poweroff headers are great can you change the tss.h -> tasksegment.h

**Comment by biggboy021** [comment]
ok

**Comment by krishpranav** [comment]
great! __MERGED__

**Comment by biggboy021** [comment]
THANKS

**Pull request merged**
