### PR TITLE
libabi: system funs

### PR DESCRIPTION
**Pull request by evilbat831**
hi @krishpranav I have added system funs 

added system-status, system info(kernel name, release, build, machine name), #defined systeminfofieldsize(65)
author: evilbat831
https://github.com/evilbat831

### CODE REVIEW

**Comment by krishpranav** [comment]
hi @evilbat831 after a long time giving a pr great!!.
let me check it out

**Comment by evilbat831** [comment]
yes due to some works

**Comment by krishpranav** [comment]
ok let me check it out

**Comment by evilbat831** [comment]
👍

**Comment by krishpranav** [comment]
great work & all checks have passed great work!!

**Comment by krishpranav** [comment]
__MERGED__

**Comment by evilbat831** [comment]
thanks!!

**Pull request merged**
