### PR TITLE
unix devices headers

### PR DESCRIPTION
**Pull request by Alex5xt**

### CODE REVIEW

**Comment by Alex5xt** [comment]
hi sir i have added unix device headers

**Comment by krishpranav** [comment]
ok i will review it and tell you

**Comment by Alex5xt** [comment]
ok sir

**Comment by krishpranav** [comment]
good i appreciate your work 👍🏻

**Comment by Alex5xt** [comment]
thanks sir

**Comment by krishpranav** [comment]
merged!! 👍🏻

**Comment by Alex5xt** [comment]
👍

**Pull request merged**
