### PR TITLE
Tests: datetime test case & rename api test

### PR DESCRIPTION
**Pull request by Lalucas20**
hello, i am Lucas i am new to open source project just saw your project and added a datetime test case and rename api_test.cpp to apitest.cpp.

THANKS.

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @Lalucas20. that's great to hear that your first contribution to open source project is mine.

**Comment by krishpranav** [comment]
very great

**Comment by Lalucas20** [comment]
yea

**Comment by krishpranav** [comment]
let me review it and tell u

**Comment by Lalucas20** [comment]
sure!

**Review by krishpranav — CHANGES_REQUESTED** [review]
change uint8_t -> uint32_t

**Comment by Lalucas20** [comment]
ok wait for few min

**Comment by krishpranav** [comment]
GREAT WORK!! APPRECIATE

**Comment by Lalucas20** [comment]
thanks

**Comment by krishpranav** [comment]
__MERGED__

**Review by krishpranav — APPROVED** [review]
LGTM

**Pull request merged**
