### PR TITLE
some headers req

### PR DESCRIPTION
**Pull request by OliviaCE**

### CODE REVIEW

**Comment by OliviaCE** [comment]
hi @krishpranav I've added some headers require for x86 check it out.

**Comment by krishpranav** [comment]
hi @OliviaCE your going good!! actually the things that your adding is awesome

**Comment by OliviaCE** [comment]
thanks

**Comment by krishpranav** [comment]
are you a It staff??

**Comment by OliviaCE** [comment]
> are you a It staff??

no actually I am a school girl

**Comment by krishpranav** [comment]
ohh ok that's a great thing,
coming back to the code 
I will check review the code and tell you

**Comment by OliviaCE** [comment]
ok 👍

**Comment by krishpranav** [comment]
AWSOME WORK __MERGED__

**Comment by OliviaCE** [comment]
😄

**Pull request merged**
