### PR TITLE
lint

### PR DESCRIPTION
**Pull request by nuke123-sudo**
hi @krishpranav I've added some lint automation functions check it out

### CODE REVIEW

**Comment by krishpranav** [comment]
hi @nuke123-sudo I will review it and tell you

**Comment by nuke123-sudo** [comment]
ok sure

**Comment by krishpranav** [comment]
the python & bash script work's are awesome appreciate it 👍🏻

**Comment by nuke123-sudo** [comment]
thanks @krishpranav

**Comment by krishpranav** [comment]
__MERGED__

**Pull request merged**
