### PR TITLE
Fuzzing functions

### PR DESCRIPTION
**Pull request by johnsmith5c12**
Things added:
pgm loader
png loader
ppm loader
quoted printable parser

### CODE REVIEW

**Comment by johnsmith5c12** [comment]
hi @krishpranav I have added some fuzzing values check It out

**Comment by krishpranav** [comment]
great work I've reviewed it! 👍🏻

**Comment by krishpranav** [comment]
__MERGED__

**Comment by johnsmith5c12** [comment]
thanks

**Pull request merged**
