### PR TITLE
fuzzing

### PR DESCRIPTION
**Pull request by antonystevanson**
Things added:
Fuzzer:
hebrewdecoder
icoloader
imapparser
jpg loader
latin1 decoder
latin2 decoder

### CODE REVIEW

**Comment by krishpranav** [comment]
hi @antonystevanson I will review it

**Comment by antonystevanson** [comment]
ok sir

**Comment by krishpranav** [comment]
great work @antonystevanson __MERGED__

**Comment by antonystevanson** [comment]
thank you @krishpranav

**Pull request merged**
