### PR TITLE
kernel: drivers ps2mousedriver header

### PR DESCRIPTION
**Pull request by Lalucas20**
hey @krishpranav i have added ps2mouse in a driver 
you can use this header to create ps2 mouse functions 

regards
- lucas

### CODE REVIEW

**Comment by krishpranav** [comment]
@Lalucas20 will go through your changes and update you. Thanks for this pr!!

**Review by krishpranav — CHANGES_REQUESTED** [review]
the driver namespace is not required!. so can you please remove the 
```c++
namespace driver {}
```
?

**Comment by Lalucas20** [comment]
hey krish i have change the thing you requested

**Comment by krishpranav** [comment]
good ones __MERGED__!!

**Pull request merged**
