### PR TITLE
swap little endian tvalue

### PR DESCRIPTION
**Pull request by nuke123-sudo**

### CODE REVIEW

**Comment by nuke123-sudo** [comment]
hi @krishpranav added some tswap endian value check it out.

**Comment by krishpranav** [comment]
will check it out

**Comment by krishpranav** [comment]
so you have added some swap bytes right

**Comment by nuke123-sudo** [comment]
yea

**Comment by krishpranav** [comment]
ok thanks for adding this stuff need to develop. merged!!

**Pull request merged**
