### PR TITLE
fixme: main CMakeList 

### PR DESCRIPTION
**Pull request by NukeWilliams**
gn -> cmake
added main cmake file for building this whole project
fixme: add your cmake current list dir here
issue: #105

### CODE REVIEW

**Comment by NukeWilliams** [comment]
hi @krishpranav so I have added the main cmake list require for building pranaOS so I hope you like it and
# Note:
```
need to add the build instructions :) 
```

**Comment by krishpranav** [comment]
hey @NukeWilliams this is a great work but I think so need to put some effort in adding rules in cmake right?

**Comment by NukeWilliams** [comment]
yes sir!!

**Comment by krishpranav** [comment]
ok great work waiting for the checks to pass!!

**Comment by NukeWilliams** [comment]
sure :)

**Comment by krishpranav** [comment]
__MERGED__

**Comment by NukeWilliams** [comment]
👍

**Pull request merged**
