### PR TITLE
libcore: string header

### PR DESCRIPTION
**Pull request by biggboy021**
hey @krishpranav i have created core lib
lib core will be used for manythings for memoperations, filesystem handling, errorhandling like this functions we can implement in that now i have added string functionality[version] so can you check it?

author: @biggboy021

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @biggboy021 thanks for adding this one let me check it

**Comment by krishpranav** [comment]
hey @biggboy021 you have changed the namespace 
- ak/string.h
```c++
namespace pranaOS {} -> namespace String {}
```

great one!

**Review by krishpranav — CHANGES_REQUESTED** [review]
pls change the filename in libcore from string.h -> version.h it would be great full

**Comment by biggboy021** [comment]
i have changed that thing !

**Comment by krishpranav** [comment]
great!! __MERGED__

**Comment by biggboy021** [comment]
thanks!

**Pull request merged**
