### PR TITLE
workflow: added a new workflow for checking markdowns

### PR DESCRIPTION
**Pull request by evilbat831**
hi @krishpranav i have added a markdown lint checker for pranaOS repo make sure to check it out :)
- @evilbat831

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @evilbat831 the markdown lint check workflow you have added is great :) 
good work

**Comment by krishpranav** [comment]
waiting for the checks for this particular pr :)

**Comment by evilbat831** [comment]
hey @krishpranav thanks for the feedback you have told i just saw this workflow in many repo including your learncpp repo. So I just added this workflow for checking no issues with the markdown files :)

**Comment by krishpranav** [comment]
that's a great thing 
__ALL CHECKS PASSED__
__MERGED__

**Comment by evilbat831** [comment]
👍

**Pull request merged**
